### ISSUE TITLE
Sign up student page should also have the possibility to enter the class code .

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#144]
This was originally part of issue #122.  

I completed this first and separated it from Issue #122 because there is a lot more detail that needs to be discussed for the 'creating a link for student to login' part of the issue.

**Comment by IvonArroyo** [comment]
I am thinking that, for the time being, we should have the following text **somewhere** in the Teacher Tools. 

If you want to have students create usernames by themselves (for instance, this is a good option if doing distance learning), you can make the following text accessible to the class (through Google Classroom or email):

**Dear Students,

We will use a platform tIo practice math problem solving, called MathSpring. In order to create  a username, you have to follow this link:

http://mathspring.org/ms/WoAdmin?action=UserRegistrationStart&var=b&startPage=LoginK12_1_&classcode=1608_
**

One possibility is that we split the **manage students** tab into 'Manage Students' and 'Create Usernames'. Otherwise, we could place it at the top of 'Manage Students', for the time being. 

--Ivon

--

**Comment by FrankSylvia** [comment]
Please send me the email or link for today's meeting.
