### ISSUE TITLE
Examples: Playing the sound of the question

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#17]
We had an issue with students not even reading the question of the Examples. I think that  Playing the sound of the question immediately, for problems that are examples should help with this issue.

We should do this for HTML problems, I know that this is too hard to solve for FLASH problems, which anyways should be reimplemented and will be disabled soon, so don't worry about those. 

--Ivon

**Comment by IvonArroyo** [comment]
Issues #16, #17 and #87 are all related.

**Comment by FrankSylvia** [comment]
Ivon, 

This issue is working for the case where the student clicks the 'Show example' button.  And will be released to Production.

It does not work automatically when the student is shown an example when starting a new topic in the 'My Progress' page.  If this also a requirement, please change the milestone back to 'Work in Progress' else change it to 'Ready to Close'.

Thanks

**Comment by FrankSylvia** [comment]
It should work automatically when the student is shown an example when starting a new topic in the 'My Progress' page.

**Comment by mkartik** [comment]
This issue has been fixed as part of #233.

**Comment by WillRebel** [comment]
The audio automatically plays when a student is shown an example when starting a new topic in the 'My Progress' page.

**Comment by WillRebel** [comment]
The next step button is immediately below the character's desk vertically.

**Comment by FrankSylvia** [comment]
The idea for this presentation was to forced the student to at least look
at and hear every hint (step) of the example.

Originally the done button was the only button on the page.  Since 'done'
would no longer be an option until all hints were displayed,
I chose the current presentation which enforce the desired sequence by
displaying 'play next step' until there are no more steps then
'done' .
