### ISSUE TITLE
Class Summary Per Common Core Cluster - red and orange color usage

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#200]
I normally think of red as worse than orange. Is it possible to change the scale so that challenging is red and really hard is orange?

**Comment by FrankSylvia** [comment]
Ivon,

I believe I just reversed this for Erik.

In any event, I need to review this while it is displayed on the screen to get this straight.

Frank

**Comment by IvonArroyo** [comment]
The labels are incorrect also, the TEXT of the key is the opposite than it should be. <20% correct should go with RED.
This one is a high priority.

**Comment by wlee-umass** [comment]
Will Lee testing

**Comment by FrankSylvia** [comment]
This looks correct to me.  Would some please verify?

**Comment by perspegrity5** [comment]
Colors seem to be working.  Later when I clicked on 'Class Summary Per Student Per Topic' i got an error window before the system completed the task.  screen shot attached. There are no topics shown in the display.  It is probably because some of the topics that were used are now inactive. I was logged in as ivon and looking at the "6th grade class". If that is an issue we need to do something about it as our set of topics has recently changed a lot. 

I would also suggest that "Home" menu say "Home (list of classes)" to be more self-evident.

**Comment by wlee-umass** [comment]
Yes. I agree with the Common Core Cluster. I randomly sampled few classes on top of the 1 class Frank suggested. I could see at least the labels are consistent in other classes also. And looks like orange matches the percentages too
