### ISSUE TITLE
'Distance Signup' user has confusing option at first login

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#230]
On first login, a distance user is presented with an empty form to enter name and first initial.  The student has already entered a first and last name.  If the student accepts  the empty form, the student's name will be erased.

Should we bypass this form for the case where the student already has a name in the db?

As a side note, the form description implies a lot more than it delivers as far as making the system friendlier.

**Comment by FrankSylvia** [comment]
At First Login intervention, pre-existing names from Manage Student Info or Distance learning signup will be displayed to the student.  If there are no pre-exsiting data, student will be presented with empty form, and asked to enter his/her name.

Rest:
Create a class with some students.  
1. Edit Student info to give some students names.
2. Leave some names blank.  
3. Add a student using Distance Learning signup.
Login with student from each group (1-3) and verify expected behavior.

**Comment by SkyRebel-mass** [comment]
First Login intervention behavior works as expected. More detail is below. For the future, what information would you like me to report?

I tested 3 sign up options, 2 users each.
1) First Time User who was given a username and the class code, with pre-existing name information.
    The name correctly populates with first name and last initial, when the user accepts this information it overwrites the last name with the initial in the student information section of the Teacher tools.
2) First Time User who was given a username and the class code, without pre-existing name information.
    The system asks for a name, when the user submits the information the system saves first name and last initial even if a last name was typed.
3) First Time User who followed the link and created a new username.
    Creating an account works as expected. However, the next page (Your Mathspring user account has been created) shows a blank first and last name, while showing the Teacher, Class, and username. Signing in after that requires using the room code as a password and works the same as User type number 1 (First time user, with username, class code, information).

Additional notes:
1) On the "Your Mathspring user account has been created" page, every field is capitalized except "username". Is that intentional?
2) Name and initial capitalization matches whatever the student types. I assume this is intentional, and allows for lowercase first names, and random capitalization within the name.
3) Is it intentional that the default password remains 1633 with no way for the student to change the password? I was able to change passwords using the Teacher Tools for already created accounts.

**Comment by IvonArroyo** [comment]
I will set this as Ready to Close.
