### ISSUE TITLE
Default topics activated when a class is created

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#232]
When a new class is created, a lot of topics are set by default.
Could we please just activate one topic? That way, the teacher has to move forward into activating others, not into deactivating, which seems like going backwards.

**Comment by mkartik** [comment]
Is there any specific topic we would like to activate by default, when a new class is created? Or just activating the topic with Order 1 would do.

**Comment by IvonArroyo** [comment]
As long as it has problems for the grade level indicated by the teacher (e.g. 6th grade, then shooou) Just activating the topic with order 1 would do.

**Comment by WillRebel** [comment]
Creating a new class defaults to:
Area of polygons: no grades above/below, grade 6, english, 2020 (repeated twice) 2021 (one time)
above and below 3 grades: still area of polygons
Expressiones Numéricas y Operaciones: no grades above/below, grade 6, spanish, 2020

Creating a class for the next year auto archived it, is that intentional behavior?

**Comment by IvonArroyo** [comment]
Hi Will,

Creating a new class should NEVER go into Archived, that is a bug.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by IvonArroyo** [comment]
Creating a new class should never have two languages, only the language
specified in the Configuration of the class.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by WillRebel** [comment]
Sorry that I wasn't clear. The class with Expressiones Numéricas y Operaciones was a separate class that I created to make sure that it worked for the Spanish language as well.

**Comment by FrankSylvia** [comment]
Creating a new class should NEVER go into Archived, that is a bug.

I had put next years classes into the archive so that they would not be confused with this year's classes in the 'Existing Classes' set.  When the school years changes to 2021, the 2021 classes would automatically show up in 'Existing Classes' and 2020 classes would automatically move to the 'Archived Classes'.  We spoke of this when I modified the Home page.

It is a one-liner change to revert this functionaltiy.  Keep in mind that there will be no way to distinguish this year's classes from next year's classes  in the 'Existing Classes' set on the Home page.  

In either case, I think it would be good to show the 'School Year' in the class thumbnail.

**Comment by IvonArroyo** [comment]
Hi Frank,

Please revert the functionality so that we don't automatically place
classes into archived.
Agreed, it would be good to show the School Year in the Class thumbnail.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002
