### ISSUE TITLE
Make a CRON job to automatically move the PROD database into the DEV database

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#239]
Hi all, we are at the content development meeting talking about testing.

We agreed that it would be ideal to Make a CRON job to automatically move the PROD database into the DEV database, so that the testers can continue using their own user names and alike, and see similar content.

We could move the DB once a week.

--Ivon

**Comment by FrankSylvia** [comment]
I think it would be advantageous to document our approach to the Software Development Life Cycle (SLDC) and use it as a basis for these sorts of changes.

The way I see the 'as-is' view, we have un-coordinated changes entering our SDLC from 2 sources, MS Admin and MS Development.

MS Admin development delivers problem definitions and content via the Production database content.  Do they test their new content there?

MS Development delivers code via Github.

There is also a third element, and that is changes to the DB schema.  We need to accommodate this into any SDLC strategy.
The challenge for issue #296 is to ensure the changes are not over-written on the Dev DB.
One approach might be to have MS Development make changes to the Prod database directly. (Tom has recently asked if he could do this) The changes would likely not impact the production server usability, since the features that would use the new schema would not be on the Prod server yet.

Another approach would be to make sure the scripted schema changes provided by MS Development remain available to be re-run each time the DB reverts to the Prod version.  (They are currently erased once applied.)

Coordinating releases between the two groups would likely be troublesome.

Fianlly, a long term solution might be to move the MS Admin tables into their own DB.  This would provide a pathway for the two sub-systems to evolve on their own schedules.

Please comment on this.

**Comment by IvonArroyo** [comment]
I think we should discuss this at a meeting.
I will add it to the agenda

**Comment by IvonArroyo** [comment]
These are the tables that need to be moved to test better the system on dev.mathspring.org as it continues to fail and miss problems and show blank screens when we test:

probstdmap 
hint 
problemgroup 
quickauthformattemplates 
probprobgroup 
overallprobdifficulty 
standard 
(now also topicstandard?)
problemlayout 
problemmediafile 
problem 
cluster 
problemanswers


This is a command that can export those tables JUST from the command line:
mysqldump -u MathspringServer -p wayangoutpostdb  probstdmap hint problemgroup quickauthformattemplates probprobgroup overallprobdifficulty standard problemlayout problemmediafile problem cluster problemanswers > Contentdump2020-08-03.sql

**Comment by IvonArroyo** [comment]
To dump from the command line:
>> mysqldump -u MathspringServer -p wayangoutpostdb auth_user > Contentdump2020-08-04-auth_user.sql

To retrieve from the command line:
 >> mysql -u MathSpringServer -p wayantoutpostdb < Contentdump2020-08-04-auth_user.sql

**Comment by IvonArroyo** [comment]
Kartik, I believe you were working on creating a script for this? Is this correct?
We really need the dev server to have much newer content.

**Comment by mkartik** [comment]
Hi Ivon, yes, I have formulated a way (using MySQL Workbench) to move specific tables from the prod database into the dev database. As we discussed in the meeting, we were waiting while Frank sets up his local database, to test the migration.

**Comment by mkartik** [comment]
--Getting the updated records from the production Database (you will be prompted to enter the password)
mysqldump -h wayangoutpostdb.com5thrjrv4i.us-east-1.rds.amazonaws.com -u altUser -p wayangoutpostdb probstdmap hint problemgroup quickauthformattemplates probprobgroup overallprobdifficulty standard problemlayout problemmediafile problem cluster problemanswers > Contentdump_prod2020-12-15.sql

mysqldump -h dev-wayangoutpostdb.com5thrjrv4i.us-east-1.rds.amazonaws.com -u altUser -p wayangoutpostdb probstdmap hint problemgroup quickauthformattemplates probprobgroup overallprobdifficulty standard problemlayout problemmediafile problem cluster problemanswers > Contentdump_dev2020-12-15.sql

-- Update the tables in the local database (you will be prompted to enter the password)
mysql -u root -p prodwayang < Contentdump_prod2020-12-09.sql

--  Update the tables in the development database (you will be prompted to enter the password)
mysql -h dev-wayangoutpostdb.com5thrjrv4i.us-east-1.rds.amazonaws.com -u altUser -p wayangoutpostdb < Contentdump_prod2020-12-15.sql

**Comment by FrankSylvia** [comment]
The CRON weekly automation part of this request cannot be accomplished because a password must be entered at the command line
