### ISSUE TITLE
Font & Image Size difference between rose and aws

### ISSUE THREAD

**Issue by tuotuoZ** [center-for-knowledge-communication/mathspring#246]
Content creators feel the font in the new aws mathspring a lightly different and bigger than the rose one, which causes some layout problem. The screenshot is below:
<img width="1440" alt="2500_Rose" src="https://user-images.githubusercontent.com/40042621/92647506-fd3f2e00-f2b5-11ea-8fd1-ea1f03601ff2.png">
<img width="1440" alt="2500_AWS" src="https://user-images.githubusercontent.com/40042621/92647513-fe705b00-f2b5-11ea-8649-9303308db74c.png">
<img width="1440" alt="2470_Rose" src="https://user-images.githubusercontent.com/40042621/92647518-003a1e80-f2b6-11ea-91bf-6b08b6968a42.png">
<img width="1440" alt="2470_AWS" src="https://user-images.githubusercontent.com/40042621/92647525-00d2b500-f2b6-11ea-8435-c339fd288598.png">

**Comment by tuotuoZ** [comment]
I am still waiting for feedback on how we should solve this. I will update once the solution is settled.

**Comment by tuotuoZ** [comment]
Content creators want to restore the font back to the rose version. It should be a simple fix, right? You just need to copy the .css file from the rose server to the aws server.

**Comment by tuotuoZ** [comment]
This is a high priority issue. Somehow, I cannot change the label of the issue. I think only the repo owner can assign labels here.

**Comment by FrankSylvia** [comment]
Eventhough the font-size was not changed, the inherent size of Comic Sans seems to be taller than the original fonts.

Do we want to revert to the original font?

**Comment by tuotuoZ** [comment]
From Danielle's reply earlier in the week, I think yes. We can revert to the original font.

I am a little confused here, who designed to use this new font in aws? Ankit?

**Comment by FrankSylvia** [comment]
Hi Ankit, Ivon wanted something the kids would like. I didn't change the
font size, but the output is still taller.

**Comment by ankitrgupta1** [comment]
Hey Frank,

If you are asking that did I change anything, then the answer is no. I
haven't touched Mathspring code since I left.

You can check the last update to the file if you want to see when and who
changed it.

Let me know in case you need any further information or help regarding
anything.

Thanks & Regards,
Ankit Gupta

**Comment by FrankSylvia** [comment]
Sorry I was unclear. The file wasn't changed after my edit. The font-sizes
were not changed at all.The Comic Sans font family seem to just be taller.

**Comment by ankitrgupta1** [comment]
Hey Frank,

As per what I see in the screeshots attached, to me it appears that the
rose version do not have the change of font which we are speaking of.

If that is the case then the decision would be, either we deploy the same
version on rose server or we change the version which we have on our
Mathspring.

I would let Professor to decide over it.

In case my assumption is not correct, then you may need to look more into
it.

Thanks & Regards,
Ankit Gupta

**Comment by IvonArroyo** [comment]
Hi all, it was my fault. I asked Frank at some point to change the font to Cabin, which is more kid friendly.
But the content developers were developing on rose, an previewing their problems with a different font, times new roman.
I am fine with either of these possible solutions:
1. Either we try to reduce the Cabin font by half a point (and no more, otherwise it will be too small)
2. We revert back to times new roman.

**Comment by FrankSylvia** [comment]
Hi all,  actually I'll take blame for this.  The original request was for Cabin or Comic Sans and I chose Comic Sans.  I didn't realize there would be a difference because the font-size was unchanged and I'm not a font expert.  I also didn't make the connection that this was causing the off-screen symptom. 

I have changed to 'Cabin' font and everything looks really good. (on my system)

I suggest we go with that through a round of testing.

I think it would be a good idea to diff the files that are theoritically the same on rose and aws, e.g. quickAuthProblem.css.

Thanks team for all the feedback on this.

**Comment by IvonArroyo** [comment]
Hi Frank, I see all of the problems with Times New Roman instead of Cabin or Comic Sans.

**Comment by IvonArroyo** [comment]
probstdmap 
hint 
problemgroup 
quickauthformattemplates 
probprobgroup 
overallprobdifficulty 
standard 
(now also topicstandard?)
problemlayout 
problemmediafile 
problem 
cluster 
problemanswers

**Comment by FrankSylvia** [comment]
Are you on dev server?

Did you clear your browser file cache?  the change was in
quickAuthProblem.css

Also please see my #Mathspring slack request?

**Comment by FrankSylvia** [comment]
When a font is not available the browser uses a default font, i.e Times Roman.  Do we have someone on the team who is font-savvy.  I did a little research but if someone knows what they're doing it would save a lot of time.

**Comment by IvonArroyo** [comment]
OK, I have been doing a bit more research. Here are three screenshots: one of mathspring.org, one of rose.cs.umass.edu, and one of dev.mathspring.org. They all look different! There is ONE single resolution is on my screen, one same browser, 3 tabs. Look at these and let's discuss what is going on:

<img width="1434" alt="Screen Shot 2020-09-18 at 2 13 32 PM" src="https://user-images.githubusercontent.com/5631787/93631496-b0e0a600-f9b9-11ea-8bce-c2a0af466697.png">
<img width="1439" alt="Screen Shot 2020-09-18 at 2 13 24 PM" src="https://user-images.githubusercontent.com/5631787/93631500-b2aa6980-f9b9-11ea-8948-5261199751ba.png">
<img width="1432" alt="Screen Shot 2020-09-18 at 2 13 17 PM" src="https://user-images.githubusercontent.com/5631787/93631502-b3430000-f9b9-11ea-88a7-b2957da4a8f9.png">

**Comment by IvonArroyo** [comment]
That is to the bottom of my browser window. This means that:

All of them seems to be resizing the location of elements to fit an area of the screen (verified, as you resize the window, the location of everything changes to try to fit better on the screen, including image size).

Image size does not change with the resizing of the browser window.

Still I can see that mathspring.org has larger images.
I can also see that dev.mathspring.org has larger font even in the MENUS than the other two.  That might be why the character doesn't fit in the screen, given the same resolution.

**Comment by IvonArroyo** [comment]
With the new improvements the large images now fiiit into the window and don't fall off.
However, the images that were readable before are now too small! Karttik I think was working on this.
