### ISSUE TITLE
Replay button, when no hints are clicked yet, gives an awkward hint

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#306]
There is an awkward behavior when you click on the "Replay Button" and there are no hints shown yet . Check it out. Sometimes a user can click it by accident as it is very close to the "Hint" button --that is what happened to me.

The behavior should be either: Do nothing (ideal). or Play the first hint, including the TAB of Step 1.

**Comment by FrankSylvia** [comment]
It looks like the Replay Button presents the last hint displayed. Is that the proper functionality?  When a hint has not been displayed yet, it seems to remember the last problem's hint name when no hint has been dislayed for the current problem.

I'm going to initalize the current hint variable when the pooblem is prepared for viewing.

**Comment by IvonArroyo** [comment]
Yes, that is the correct functionality, however, when there is no hint yet,
there is a hint that shows up and it is unclear what hint that is..

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her

**Comment by FrankSylvia** [comment]
A couple of questions:

It appears that Flash problems have no Replay capability.  Is that true?

For html problems, 'Replay Hints' always replays the last hints seen by clicking the 'Play Hints' button, even if  the student had most recently selected a previous hint by clicking a 'Step # tab'.  Is that ok?

If you click 'Replay Hints' before clicking 'Play Hint(s)',  I have it putting up a message, "No hints seen yet".  Is that ok?

**Comment by IvonArroyo** [comment]
Hi Frank,

We don't care about flash problems as we have disabled flash for good. Any
code that tries to consider flash problems can be removed.

"For html problems, 'Replay Hints' always replays the last hints seen by
clicking the 'Play Hints' button, even if the student had most recently
selected a previous hint by clicking a 'Step # tab'. Is that ok?"
That is OK to me, I think it is reasonable.

"If you click 'Replay Hints' before clicking 'Play Hint(s)', I have it
putting up a message, "No hints seen yet". Is that ok?"
I would change that message to: "You have not seen any hints yet. Make sure
you click on the 'Hint' button to see the first hint for this problem.'

--Ivon
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her

**Comment by WillRebel** [comment]
**Overall results (notes below):**
_Very inconsistent behavior:_
Show first hint (e.g. 2022,2625,2682)
Show second hint (many, didn't record numbers unfortunately)
Does nothing (1959)
Shows all hints stacked (2002, 1977)
Shoes first hint without the step 1 tab marker (1967)

_Consistent behavior:_
Continues to read hint after problem is solved-apparently this is normal behavior in the system based on getting a hint
Counts as SOF rather than SHINT


_Testing notes_
1) It seems to mostly default to the second hint in the problem (showing the second hint before the first), but doesn't count towards hints. In other words, clicking the replay hint and then solving the problem returns SOF which is not good.

2) problem 1959 does nothing when you click it: probably better behavior

3) problem 1969: replaying hint then selecting the answer before it finishes reading leads to the system continuing to read the hint.

4) problem 2022: first problem where hint 1 is played instead of hint 2
5) 2625 plays hint 1, still gives SOF

6) 1967: shows hint 1 without the step 1 "tab" marker

7) 2002: shows all hints stacked vertically , gives SOF
![image](https://user-images.githubusercontent.com/71284897/99990898-03ec2600-2d7a-11eb-8f11-eedbe9df5aec.png)

8)1977: first step, SOF

9)1869: weird hint appears to be 1 and most of 2
![image](https://user-images.githubusercontent.com/71284897/99991147-47469480-2d7a-11eb-97c3-e03b9fb2e4c3.png)
