### ISSUE TITLE
TeacherTools Bug with Inactive Classes

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#31]
I set several classes as isActive=0 (per Danielle's wishes) but she still sees some of them listed in the teacher tools on the home screen. Danielle is  teacherId=738; I have changed the names of 12 dummy classes to have TODELETE in the name. You can see that some of these still appear in the 'Existing Classes (New") section.  It is not clear what "Existing Classes (Archived)" means--is that just older than some date, or should it also list the isActive=0 classes?

![Screen Shot 2019-11-19 at 9 03 39 PM](https://user-images.githubusercontent.com/6215165/69203379-1e117980-0b12-11ea-8ed1-d932ac04367c.png)

**Comment by FrankSylvia** [comment]
Fixed by changes fir issue #156.  

Classes that are isActive = 1 are displayed in the Active section.

Classes that are isActive=0 or (isActive=1 and older than the current year), are displayed in the Archived section.

Classes may be set isActive = 1 by the archive button.

Once in the archived section, classes can be deleted from the db with the delete button.

I think this addresses issue #31.
