### ISSUE TITLE
Security Issue: Unauthorized access to another teacher's class

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#322]
We talked today that the next step in updating security in the Teacher Tools would be to hide the classid from the URL, the same way that the teacherid was hidden.

**Comment by FrankSylvia** [comment]
This issue was addressed by Issue #54.  Unfortnately while making changes to split the Class View page into two separate JSPs, I broke the URL security changes.  It is now repaired and improved to not allow any modification to the classID in the URL.  Changing the classId in the URL will display an error message "URL error class ID Modified" and force the user to log back in.  The event is also logged in the Teacher Activities Log.

**Comment by WillRebel** [comment]
class id is displayed
http://dev.mathspring.org/ms/tt/tt/viewClassDetails?classId=1641&currentSelection=classHomePage
changing it kicks me to:
![image](https://user-images.githubusercontent.com/71284897/101655205-f637d100-3a06-11eb-8fb4-94a7f60517ee.png)
