### ISSUE TITLE
Topic: [See MultiLangTable--old: Multiplication/Division of Decimals] | Standards: 5.NBT.7.md

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#329]
I was testing one of Lisa O'Connors classes, and I see that at the top of the Practice area it says:

Topic: [See MultiLangTable--old: Multiplication/Division of Decimals] | Standards: 5.NBT.7.md

This is topic # 66.

I am not clear where this is being pulled from, but I bet it is the wrong place?

**Comment by IvonArroyo** [comment]
I just verified that text is stored in the "description" of the problemgroup table.
Instead, you should look at the "problemgroup_description_multi_language" and display the pg_language_name field:

select pg_language_name 
from problemgroup_description_multi_language
where pg_pg_grp_id = 66

Of course that will give you the full string with all the languages, you have to extract the english one from over here.
Let's please default to English! So that we don't have any more spanish problems.

**Comment by perspegrity5** [comment]
Since I updated the topic information recently when the code us pulling from the wrong field it will say " [See MultiLangTable--old: ...".  So that is why it is showing up now. This will give us a more clear indication of such bugs in the code.  Theoretically we switched from using the topic Description or Summary to the info in the multilanguage table about a year ago, but there may still be parts of the code looking at the obsolete field(s).

**Comment by FrankSylvia** [comment]
The report 'PerStudentPerProblemSet' aka 'PerStudentPerTopic' now uses problemgroup_description_multi_language table for topic names.  When formatting the presentation of topic names for the report the column names are trimmed of spaces.  In the db, topic id 24 "Exponents and Radicals" contains a 'non-breaking spaces character, unicode 'C2 AO' which was not removed when the when trimming  for a normal space character.  This caused a mis-match between to uses of that data in the chart.js utility.  The character is visually undetectable unless you look at the text in a hex-format.  The utility reports in an alert, "unmatched column error'".

I have replaced the offending text with a version using the hex 32 space character in both prod and dev DBs and the report is now working fine.  It's unfortunate that the chart.js utility is sensitive to user data in such a manner.

**Comment by FrankSylvia** [comment]
How are topics currently managed?  Do we want to formalize this?  Perhaps the msadmin team could have a screen for this?

**Comment by perspegrity5** [comment]
Can you clarify your question Frank? Are you asking that the msadmin tool ensure that , for example, topic names (perhaps all text) limit the character set to ascii plus spanish characters? Should we be worrying about this for other fields, like class names?

**Comment by FrankSylvia** [comment]
Found several more places where the "problemgroup_description_multi_language" table is not beong used.

**Comment by FrankSylvia** [comment]
Hi Tom,

Some of the Topic-centric multi-lingual changes had been done before I got
here.  I completely dropped the ball on what was left to do there. Your
idea of changing the obsolete text location was perfect for helping me
catch up on that task.

The problem with the unexpected characters in the topic name was a separate
issue.  Because of the way data are marshalled for the topic report, there
was a mismatch created between the column header and the name of the
associated source data location.  It was a difficult problem to diagnose
because it was wrecking the internal algorithm of the chart.js utility. So
far, there was only one such problem.

My question was just about how topic information is managed in the project.
You seem to have gotten stuck with that and I wondered aloud whether a
screen in the msadmin tools might be useful to offload that from you.

One other thing, there are some Spanish characters that are not rendering
correctly on the browser.  We have seen that in the past whenI was
converting the rest of the app to be multilingual in Spanish.  I'll try to
correct that using google translate which seems to output a good character
set for our usage.

Finally, I am creating a Spanish class on the dev database for testing.
Once I'm finished my testing. I'll publish the teacher for my test classes
to facilitate additional testing by others.

Thanks for your help.

Frank
