### ISSUE TITLE
Adding correct answers somewhere (in 'Manage Topics' page?)

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#378]
One of the teachers today said she couldn't figure out the answer to one of the problems and wants to check what answer it expects.

This seems reasonable, obvious. 
It would make sense that the correct answers are in the 'Manage Topics' page, so that they can find it by looking at the topic's problems in the Teacher Tools.

Could we do this? Could we do this before Frank leaves?

Let me know.

**Comment by IvonArroyo** [comment]
One possibility is to show the possible answers in the "preview" window, where the problem gets displayed

**Comment by WillRebel** [comment]
It looks like this works, although it may be causing problems with the authoring tool when content creators are taking a screenshot for the problem snapshot. Is it possible to move the correct answers down a bit so that there is more whitespace available?

**Comment by perspegrity5** [comment]
NEW issue here after this was implemented:  The same previewer comes up for teachers and authors tools. Authors use the preview screen to take the screenshot that gets stored with the problem. For some problems with a lot on the screen, it is impossible to select a screen-shot area without including the answer with the clip. 

Solution (proposed):  don't show the answers in the same area (div) as the problem is in, but create a new area/div, perhaps below, to show that information.  Make it non-white so it is clearly outside the problem area.

**Comment by FrankSylvia** [comment]
![issue_378_sample](https://user-images.githubusercontent.com/46008380/107412032-1138c700-6ac4-11eb-83c8-cbf1348f87b7.PNG)

How about having the answer at the top? See link.

**Comment by WillRebel** [comment]
I think that would work since it would still allow for snapshots

**Comment by IvonArroyo** [comment]
This one is ready to close
