### ISSUE TITLE
Home Landing Page Report (Teacher Tools) changes

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#388]
Danielle had a meeting with one of the teachers, who suggested a bunch of changes to the reports.
One of them has to do with the Home Landing Page report.

- She wants to be able to enter a date range (from:  to: ) and execute the report only for that date range, in addition to the last x days.
- Change **brown** background color of the highlights of this report to something in the color palette of MathSpring. I think #7bedc7 is a better choice instead of brown.
- - Ability to download this report as CSV, given whatever the date range is that has been selected (whatever you are seeeing on the screen at the moment).

**Comment by FrankSylvia** [comment]
Hi von,

Do you want to use calendar objects for the from/to selections?

Do you want to replace brown filter backgrounds in all the report card reports? They all use the same css element.

**Comment by IvonArroyo** [comment]
Yes! That sounds good, as we talked today. Yes please replace all the brown filter backgrounds, thanks.

**Comment by FrankSylvia** [comment]
Date range and color change completed and testable.  CSV to follow.

**Comment by WillRebel** [comment]
The dates seem to work in general, although I noticed a few issues that may be due to a backend thing:

1) The Geometry table (see attached) includes problems that shouldn't have been seen since I only had 1906, 1907, 1908, and 1910 active for this class 
![image](https://user-images.githubusercontent.com/71284897/113789738-57e22080-9705-11eb-8511-129dea5ba34e.png)

2) Mastery Level is not calculating the same as on the student side (see student 2 data, compare to 3rd mastery in image 2)
![image](https://user-images.githubusercontent.com/71284897/113789793-7811df80-9705-11eb-9415-5b734ed7be39.png)
![image](https://user-images.githubusercontent.com/71284897/113789803-7d6f2a00-9705-11eb-8618-286aa97919de.png)

3) Filtering by day leads to an infinite loop in the "Class Summary per Student per Problem" page unless a student is also selected.
