### ISSUE TITLE
No session active Exception should take students to login page

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#394]
When the session times out, it currently gives an exception.
No session active Exception should take students to login page instead, so that they login again.

**Comment by FrankSylvia** [comment]
This fix handles Nosession Exceptions in TutorBrainHandler.java to catch when browser's http session has expired (30 minutes). At this point, MS no longer has access to the student's identity. This fix catches many instances where the MS smgr Session has been lost due to browser timeout. It not feasible to catch every state the user is in when timing out, but this one code location catches many. So if the user is getting no response and he/she starts clicking navigation links like "Pracitce Area" it will goes through TutorBrainHandler and send the user to the student login page.

**Comment by WillRebel** [comment]
I was unable to verify this on either dev or prod. I left an account open on each for 2+hours and they were both still able to navigate via the links and were sent to neither the exception nor the login page
