### ISSUE TITLE
Bug with creating classes in dev.

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#434]
Says Will Rebelsky:

1)
 While I was building new classes to test, I ran into the following error every time. Clicking refresh did nothing, although going back to the teacher home screen and refreshing made the class populate. Of note, however, is that clicking back and resubmitting the same form over and over led to this same error but did not duplicate the class (I still ended up with only 1 version of it). I'm not sure what's going on behind the scenes, but since it appears to be a dev only error it may not be an issue.

![image](https://user-images.githubusercontent.com/5631787/113913634-8f56d880-97aa-11eb-9e0b-c3f388cf3f74.png)

2) When trying to log in, while dev.ms was struggling to switch pages, my browser tab switched information to: image.png. I'm not sure if that matters, but I thought it was interesting.

**Comment by WillRebel** [comment]
image.png is: 
![image](https://user-images.githubusercontent.com/71284897/113929192-638d2000-97b5-11eb-81f5-5922dfab3770.png)

**Comment by FrankSylvia** [comment]
Kartik, Please look into the DB aspect of this exception.  I am working on the Page Reload part of it.

**Comment by mkartik** [comment]
Frank, the issue with the DB exception has been resolved and is ready to be tested.

**Comment by WillRebel** [comment]
When I created a new class today (dev), I first saw a large red warning to not reload. Then I ended up with the same exception report (I think)
![image](https://user-images.githubusercontent.com/71284897/116423988-c6973300-a806-11eb-9851-4b0a9d02b95b.png)

However, the class was still created

**Comment by IvonArroyo** [comment]
Will, could you please say what was the class name that you gave, and any
other info?
So that we can replicate the error.

Thanks!
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her

**Comment by FrankSylvia** [comment]
The page refresh sends a second request for a new class which coollides with the first request which is right in the middle of being processed.

This is an example of the "Don't refesh the screen or you will purchase a second it."  The reasoin we can't solve it now is because no one has been able to solve this in the past 20 years.

The task which is created is ill-formed in one of many ways depending on where the collision occured.  When this happens, the ill-formed task shoudl be 'Archived' and then 'Delete' to avoid confusion later on.

I have put warning to the user to be patient.  That's all we can do in this case.

I'm closing this issue.
