### ISSUE TITLE
CREATE CLASS and MANAGE TOPICS: Improvements to presentation of Class maintenance page

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#51]
CREATED a Class and Went to ARCHIVED.  Why is class# 1587 (on AWS) in the Archived List if this class has isActive=1?

 

Start with an empty list of topics.

Too many active topics.

Too hard to deactivate, not intuitive.

**Comment by IvonArroyo** [comment]
It is unclear if the classes go to archived when just created, maybe not, however, there is a message immediately after you create a class that is a bit confusing saying something about going to see your classes. If this message stays, it should add 'Click on HOME to go to see all your classes, and then choose the new class to upload your roster.' 

AFter I created thee class, I believe the NAME of the class at the top was incorrect (please check?) as my class was called 'Sample 6th grade' and it said something different at the top.

Also, after creating this class, it placed a lot of topics that had ZERO problems in them in the list. The topics in the list should at least have 1 problem! 

Also, I agree that it is TOO many topics in the list --Could it add just 2 topics as an example and be done, just as an example? Or otherwise, start with an empty list, and say 'You have no active topics set for the students in this class. Please activate some topics'.

**Comment by FrankSylvia** [comment]
It is unclear if the classes go to archived when just created, maybe not, 
The program currently uses Calendar year to determine Archived Classes, in addition to using isActive=0 status.
**It is possible now.  Should we disallow previous years**

When we say 'year', are we talking about School Year, that being the year at the end of the class i.e. in June?
Do we want to enforce only current School Year when creating classes?

**We are able to go directly to Home Page after creating a class, so we don't need to say "Click on HOME to go to see all your classes." Instead we should probably add "After the class is created, you will be sent to your Home Page, where you may then choose the new class to configure it, or upload your roster.'**

AFter I created thee class, I believe the NAME of the class at the top was incorrect.  **This was the case, but now that we go directly to the Home Page it is moot.**

**Comment by FrankSylvia** [comment]
Removed all topics with ZERO problems from list of active topics on "Manage Topics" page

**Comment by FrankSylvia** [comment]
Alert message after clicking Create Class button:  "After the class is created, (this may take a few moments), you will be sent to your Home Page, where you may choose to finish setting up your new class roster."

**Comment by FrankSylvia** [comment]
Most of the requested changes are complete and tested.  I'm going to close this issue and create a new one with the remaining requested changes.
These are:
Start with an empty list of topics.
Too many active topics.
Too hard to deactivate, not intuitive.
