### ISSUE TITLE
Teacher Tools: Thumbnails image size constraint

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#73]
Please constrain the size and width of an image thumbnail in the teacher tools to be no taller than 250 pixels and not wider than 400 pixels.

--Ivon

**Comment by IvonArroyo** [comment]
This applies to all the reports, and also to the "Manage Problem sets" menu item when setting up a class, or modifying it.

**Comment by FrankSylvia** [comment]
How strictly do we need to conform to the 250px by 400px image size?  There is signifant distortion.  I have experimented and found that 400 by 400 is more visiually appealing.  I'd like to release a version to the Dev/QA system so you could try it out.  Are you ok with that?  Once you see it, we can make any further adjustments very easily or go with it at 400 by 400.  I also changed a couple of the popups to appear in different relative position, e.g. top vs right, (see the Master Trajectory report, where the popups run off the bottom of the screen because the graph takes up most of the screen space. It looks better relative from the top of the problem Id link field.  While your looking this over, let me know if any other popups need to move to better locations.

**Comment by IvonArroyo** [comment]
Can we adjust only to the height and let the width adjust
proportionally/automatically, or viceversa?

------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Please look over the teacher reports for thumbnails that have been re-sized to max 400x400.  If they look good, please set the milestone status to 'Ready to cose'. Thanks.
